//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrameGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoFrameGenerator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   入力ファイル追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddInputFile {
            get {
                return ResourceManager.GetString("AddInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   絞り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Aperture {
            get {
                return ResourceManager.GetString("Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カメラ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraModel {
            get {
                return ResourceManager.GetString("CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するEXIF情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXIFInformationToDisplay {
            get {
                return ResourceManager.GetString("EXIFInformationToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   露出補正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExposureCompensation {
            get {
                return ResourceManager.GetString("ExposureCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   露出モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExposureMode {
            get {
                return ResourceManager.GetString("ExposureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   焦点距離 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FocalLength {
            get {
                return ResourceManager.GetString("FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ファイル一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputFileList {
            get {
                return ResourceManager.GetString("InputFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISO感度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ISOSensitivity {
            get {
                return ResourceManager.GetString("ISOSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レンズ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LensModel {
            get {
                return ResourceManager.GetString("LensModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルもしくはファイルが含まれるフォルダをドラッグ&amp;ドロップしてください｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageGuideDragAndDrop {
            get {
                return ResourceManager.GetString("MessageGuideDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションのプロジェクトURLを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOpenProjectUrl {
            get {
                return ResourceManager.GetString("MessageOpenProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢生成｣ボタン押下で生成を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyGenerate {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成が完了しました｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusCompleteGenerate {
            get {
                return ResourceManager.GetString("MessageStatusCompleteGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusInputFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusInputFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成しています｡({0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusNowGenerating {
            get {
                return ResourceManager.GetString("MessageStatusNowGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   撮影日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShootingDateAndTime {
            get {
                return ResourceManager.GetString("ShootingDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シャッター速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShutterSpeed {
            get {
                return ResourceManager.GetString("ShutterSpeed", resourceCulture);
            }
        }
    }
}
