<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<Product>PhotoFrameGenerator</Product>
	<VersionPrefix>1.0.0</VersionPrefix>
	<Authors>overdrive1708</Authors>
	<Copyright>Copyright © 2026 overdrive1708</Copyright>
	<PackageProjectUrl>https://github.com/overdrive1708/PhotoFrameGenerator</PackageProjectUrl>
	<NeutralLanguage>ja-JP</NeutralLanguage>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	<ApplicationIcon>Resources\ApplicationIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MetadataExtractor" Version="2.9.3" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\ApplicationIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
